In [2]:
import pandas as pd

In [3]:
data=pd.DataFrame({"a":["one","two"]*3,"b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [4]:
data.duplicated()#the last two are duplicated because the exact same sequence happened in 23 as in 45

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [5]:
data.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [6]:
data["c"]=range(6)
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [7]:
data.duplicated(["a","b"],keep="last")

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [8]:
df=pd.DataFrame({"names":["Tim","tom","Sam","kate","Kim"],"scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [9]:
classes={"Tim":"A","Tom":"A","Sam":"B","Kate":"B","Kim":"B"}

In [10]:
n=df["names"].str.capitalize()
n

0     Tim
1     Tom
2     Sam
3    Kate
4     Kim
Name: names, dtype: object

In [11]:
df["branches"]=n.map(classes)

In [12]:
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

In [13]:
import numpy as np
s=pd.Series([80,70,90,60])
s.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [14]:
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [15]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),index=[0,1,2],columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [16]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)

In [17]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [18]:
df.rename(index=str.title,columns=str.upper)

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [19]:
df.rename(index={"one":"ten"},columns={"sam":"kate"},inplace=True)
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

In [20]:
sc = [30, 80, 40, 90, 60, 45, 95, 75, 55, 100, 65, 85]
x=[20,40,60,80,100]
y=pd.cut(sc,x)#sorts them according to the intervals in x
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [21]:
y.codes


array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [22]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [23]:
pd.value_counts(y)


C:\Users\marco\AppData\Local\Temp\ipykernel_19368\1325142569.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(y)


(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
Name: count, dtype: int64

In [24]:
y=pd.cut(sc,x,right=False)
y

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [25]:
nm=["low","medium","high","very high"]
pd.cut(sc,x,labels=nm)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [26]:
pd.cut(sc,10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [27]:
data=np.random.randn(100)
c=pd.qcut(data,4)

In [28]:
c

[(0.147, 0.943], (-2.492, -0.468], (-0.468, 0.147], (0.147, 0.943], (-2.492, -0.468], ..., (-2.492, -0.468], (0.147, 0.943], (0.943, 1.925], (-2.492, -0.468], (0.943, 1.925]]
Length: 100
Categories (4, interval[float64, right]): [(-2.492, -0.468] < (-0.468, 0.147] < (0.147, 0.943] < (0.943, 1.925]]

In [29]:
pd.value_counts(c)

C:\Users\marco\AppData\Local\Temp\ipykernel_19368\2732919705.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(c)


(-2.492, -0.468]    25
(-0.468, 0.147]     25
(0.147, 0.943]      25
(0.943, 1.925]      25
Name: count, dtype: int64

In [30]:
data=pd.DataFrame(np.random.randn(1000,4))
data.head()

0         1         2         3
0  0.072811  1.724143 -0.095076 -0.435911
1  0.228198  0.723252 -1.361119 -1.218842
2  1.381506  0.011208  0.100674  0.892056
3  0.572680  0.220403  0.030332  0.399366
4  0.508678  1.698225 -0.622473 -0.894398

In [31]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.006398     0.008184    -0.008864    -0.069205
std       0.972122     0.996834     1.015627     1.033687
min      -3.394178    -3.212032    -3.035807    -3.052842
25%      -0.591413    -0.673359    -0.672895    -0.779487
50%       0.026687     0.008571    -0.070912    -0.077458
75%       0.663770     0.650596     0.686967     0.631078
max       2.931807     3.256453     2.998468     3.287332

In [32]:
col=data[1]

In [33]:
col[np.abs(col)>3]

104   -3.212032
972    3.256453
Name: 1, dtype: float64

In [34]:
data[(np.abs(data)>3).any(1)]

TypeError: DataFrame.any() takes 1 positional argument but 2 were given

In [ ]:
np.sign(data).head()

In [35]:
data=pd.DataFrame(np.arange(12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [36]:
rw=np.random.permutation(4)
rw

array([0, 2, 1, 3], dtype=int32)

In [37]:
data.take(rw)

0   1   2
0  0   1   2
2  6   7   8
1  3   4   5
3  9  10  11

In [38]:
data.sample()#randomly selects a row for a "sample"

0  1  2
1  3  4  5

In [39]:
data.sample(n=2)

0   1   2
2  6   7   8
3  9  10  11

In [40]:
data=pd.DataFrame({"letter":["c","b","a","b","b","a"],"number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [41]:
pd.get_dummies(data["letter"])

a      b      c
0  False  False   True
1  False   True  False
2   True  False  False
3  False   True  False
4  False   True  False
5   True  False  False

In [42]:
data=np.random.randn(10)
data

array([ 0.16309425, -0.43671293,  1.0560818 , -0.6318468 ,  0.83399167,
        0.93992383,  0.13688592,  1.69575242,  0.5902357 , -0.7379244 ])

In [43]:
pd.get_dummies(pd.cut(data,4))#splits data into 4 parts

(-0.74, -0.13]  (-0.13, 0.479]  (0.479, 1.087]  (1.087, 1.696]
0           False            True           False           False
1            True           False           False           False
2           False           False            True           False
3            True           False           False           False
4           False           False            True           False
5           False           False            True           False
6           False            True           False           False
7           False           False           False            True
8           False           False            True           False
9            True           False           False           False